version: '3'

services:
  app:
    build: .
    entrypoint: docker/entrypoint.sh
    container_name: ts-user-app
    ports:
      - '3002:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb
    networks:
      - user_network

  mongodb:
    image: mongo:5.0
    container_name: ts-user-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ts_user
      - MONGO_INITDB_ROOT_PASSWORD=ts_user
    networks:
      - user_network
networks:
  user_network:
